reports/urls.py
from django.conf.urls import re_path, url
from django.urls import path
from . import views
from .views import OutputData, TradeMatchView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', views.index, name='index'),
    path('datainput', views.input_data, name='input_data'),
    url(r'tradematch/$', login_required(TradeMatchView.as_view(success_url="tradematch")), name='trade_match'),
    path('output', login_required(OutputData.as_view(success_url="")), name='output'),
    path('summary', views.summary, name='summary_tab'),
    path(r'^ajax/load-purchases/$', views.load_purchases, name='load_buys'),
]

zacheqsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from zacheqsite import settings

urlpatterns = [
    path('', RedirectView.as_view(url='/reports/datainput')),
    path('admin/', admin.site.urls),
    path('reports/', include('reports.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

reports/forms.py
import json
from django import forms
from django.contrib.auth.models import User
from .models import Transaction

class TickerForm(forms.Form):
    inpTick = forms.CharField(label='Ticker on Input Sheet')
    outTick = forms.CharField(label='Stock Ticker')

    def __init__(self, user, *args, **kwargs):
        super(TickerForm, self).__init__(*args, **kwargs)
        self.user = user

class HeaderForm(forms.Form):
    HEADER_OPTIONS = ()
    for i in Transaction._meta.get_fields():
        i = str(i).replace('reports.Transaction.', '')
        choice = (i, i)
        if choice not in HEADER_OPTIONS:
            HEADER_OPTIONS += (choice),

    inpHead = forms.CharField(label='Header on Input Sheet')
    outHead = forms.ChoiceField(label='Database Header', choices=HEADER_OPTIONS)

    def __init__(self, user, *args, **kwargs):
        super(HeaderForm, self).__init__(*args, **kwargs)
        self.user = user

class BrokerForm(forms.Form):
    inpBroker = forms.CharField(label='Broker on Input Sheet')
    outBroker = forms.CharField(label='Report Broker')

    def __init__(self, user, *args, **kwargs):
        super(BrokerForm, self).__init__(*args, **kwargs)
        self.user = user

class OutputForm(forms.Form):
    brokers = Transaction.objects.values("broker")
    BROKERS = ()
    for i in brokers:
        broker = (i['broker'], i['broker'])
        if broker not in BROKERS:
            BROKERS += (broker),

    brok = forms.ChoiceField(label='Broker', choices=BROKERS)
    start_date = forms.DateField(widget=forms.DateInput)
    end_date = forms.DateField(widget=forms.DateInput)

    def __init__(self, *args, **kwargs):
        super(OutputForm, self).__init__(*args, **kwargs)


class TradeMatchForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ()

    sales = Transaction.objects.filter(type='Sell').exclude(matching='Matched').exclude(shareamount=0)
    SALES = ()

    for i in sales:
        sale = (i.prim_key, str(i.symbol) + " " + str(i.shareamount) + " Shares Sold " + str(i.tradedate))
        if sale not in SALES:
            SALES += (sale),

    saleF = forms.ChoiceField(label='Sale Trade', choices=SALES)
    all_purchases = forms.MultipleChoiceField(widget=forms.SelectMultiple, choices=(), required = False)
    matched_trades = forms.MultipleChoiceField(widget=forms.SelectMultiple, choices=())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Equity Database</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  {% load staticfiles %}
  <script src="{% static "reports/js/style.js" %}"></script>

  <style>
  body {
    margin: 0;
    font-family: Arial, Helvetica, sans-serif;
    }

  .topnav {
      overflow: hidden;
      background-color: #79258e;
    }

  .topnav a {
      float: left;
      display: block;
      color: #f2f2f2;
      text-align: center;
      padding: 10px 40px;
      text-decoration: none;
      font-size: 12px;
    }

    .topnav li {
        float: left;
        display: block;
        color: #f2f2f2;
        text-align: center;
        padding: 0px 40px;
        text-decoration: none;
        font-size: 12px;
      }

  .topnav a:hover {
      background-color: #ddd;
      color: purple;
    }

  .topnav a.active {
      background-color: #4CAF50;
      color: white;
    }

    .topnav .icon {
        display: none;
    }
  </style>
</head>


<body>
  <div class="topnav">
    <a  href="{% url 'index' %}">Home</a>
    <a  href="{% url 'input_data' %}">Data Input</a>
    <a  href="{% url 'trade_match' %}">Match Trades</a>
    <a  href="{% url 'output' %}">Output</a>
    <a  href="{% url 'summary_tab' %}">Summary</a>
    <a href="javascript:void(0);" class="icon" onclick="myFunction()">
      <i class="fa fa-bars"></i>
    </a>

    {% if user.is_authenticated %}
       <li style="float:right"><font color="white">User: {{ user.get_username }}</font></li>
       <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
     {% else %}
       <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
     {% endif %}
  </div>
</body>

<div class="col-sm-10 ">
{% block content %}{% endblock %}
</div>

</html>

templates/index.html
{% extends "base_generic.html" %}

{% block content %}

<h4>Homepage</h4>

{% endblock %}

templates/input_data.html
{% extends "base_generic.html" %}
{% load render_table from django_tables2 %}

{% block content %}
  <!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
  .inputfile + label {
      font-size: 1em;
      font-weight: 700;
      color: white;
      background-color: #79258e;
      display: inline-block;
      cursor: pointer; /* "hand" cursor */
      outline: 1px dotted #000;
	    outline: -webkit-focus-ring-color auto 5px;
  }

  .button {
      font-size: 1em;
      font-weight: 700;
      color: white;
      background-color: #79258e;
      display: inline-block;
      cursor: pointer; /* "hand" cursor */
      outline: 1px dotted #000;
	    outline: -webkit-focus-ring-color auto 5px;
  }

  .inputfile:focus + label,
  .inputfile + label:hover {
      background-color: #ddd;
      color: purple;
    }

  .inputfile {
  	width: 0.1px;
  	height: 0.1px;
  	opacity: 0;
  	overflow: hidden;
  	position: absolute;
  	z-index: -1;
  }

  section {
    font-size: 1em;
    font-weight: 700;
    display: inline-block;
    padding: 50px;
    vertical-align: text-top;
  }

  .left {
    float: left;
  }

  .right {
    float: right;
  }

  label.center {
    margin-left: auto;
    margin-right: auto;
    width: 25em;
    text-align: center;
  }
</style>

<h4>Data Input Page</h4>

  <p></p>

  <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
    <input type="file" name="datafile" id="file" class="inputfile" data-multiple-caption="{count} files selected" multiple />
    <label for="file" id="file_label">Choose a Trade File</label> <!--class = icon-->
    <br>
    <button class="button" type="submit" value="{{b.id}}" name="trade_file">Load File</button>
  </form>

  <div>
    <section style="left">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
          {{ tickForm.as_table }}
        </table>
        <button class="button" type="submit" value="{{b.id}}" name="tickUpdate">Add Ticker</button>
      </form>
      <br>
      <label class='center'>Ticker Mapping</label>
      {% render_table TickTable %}
    </section>

    <section style="right">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
          {{ headForm.as_table }}
        </table>
        <button class="button" type="submit" value="{{b.id}}" name="headUpdate">Add Header</button>
      </form>
      <br>
      <label class='center'>Header Mapping</label>
      {% render_table HeadTable %}
    </section>
  </div>

  <br>

  <div>
    <section style="left">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
          {{ brokForm.as_table }}
        </table>
        <button class="button" type="submit" value="{{b.id}}" name="brokUpdate">Add Broker</button>
      </form>
      <label class='center'>New Section</label>
    </section>
  </div>

  <div id="WaitDialog"   class="hidden" style="text-align: center">
      <img  src="static/loading_black.gif" />
      <div style="margin-top: 10px; color: white">
          <b>Please wait</b>
      </div>
  </div>

  <script>
    $("#file").on( 'change', function(){
      $("#file_label").text($(this).val());
    });
  </script>


{% endblock %}

templates/output.html
{% extends "base_generic.html" %}
{% load render_table from django_tables2 %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% block content %}

<style>
.button {
    font-size: 1em;
    font-weight: 700;
    color: white;
    background-color: #79258e;
    display: inline-block;
    cursor: pointer; /* "hand" cursor */
    outline: 1px dotted #000;
    outline: -webkit-focus-ring-color auto 5px;
    margin-left: auto;
    margin-right: auto;
    width: 20em;
    text-align: center;
}

.left {

  border:1px solid black;
}

div.pltable {
    float: left;
    width:250px;
    margin: auto;
    border: 3px solid black;
}

div.ipotable{
  clear:both;
  float: left;
  width:1000px;
  padding: 5px;
  margin: auto;
  border: 3px solid black;
}

div.sectable{
  clear:both;
  float: left;
  width:1000px;
  padding: 5px;
  margin: auto;
  border: 3px solid black;
}

div.tradetable{
  clear:both;
  float: left;
  width:1000px;
  padding: 5px;
  margin: auto;
  border: 3px solid black;
}

th, td {
    padding: 5px;
}
</style>

<h4>Reports</h4>

<div>
  <div class="row">
    <div class="col-lg-4">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
          {{ OutForm.as_table }}
        </table>
        <button class="button" type="submit" value="{{b.id}}" name="pullData">Generate Report</button>
      </form>
    </div>

    <div class="col-lg-4">
      {% render_table OpenPositionTable %}
    </div>
  </div>
</div>

<br>

<div class="pltable">
  <table>
    <tr>
      <th><h4> P&L </h4></th>
      <th>  <th>
    </tr>
    <tr>
      <td><h5> IPOS </h5></td>
      <td><h5> {{ IPO_PL }} </h5></td>
    </tr>
    <tr>
      <td><h5> 2nds/ON </h5></td>
      <td><h5> {{ Sec_PL }} </h5></td>
    </tr>
    <tr>
      <td><h5> Total </h5></td>
      <td><h5> {{ Total_PL }} </h5></td>
    </tr>
    <tr>
      <td><h5> Commissions </h5></td>
      <td><h5> {{ commis }} </h5></td>
      <td><h5> {{ Net_Perc }} </h5></td>
    </tr>
    <tr>
      <td><h5> Net </h5></td>

    </tr>
  </table>
</div>

<br>

<div class="ipotable">
  <h4>IPOs</h4>
  {% render_table ipoTable %}
</div>
<br>
<div class="sectable">
  <h4>Secondaries/Overnights</h4>
  {% render_table secTable %}
</div>
<br>
<div class="tradetable">
  <h4>Trades</h4>
  {% render_table Trade_Table %}
</div>

{% endblock %}

templates/summary.html
{% extends "base_generic.html" %}
{% load render_table from django_tables2 %}

{% block content %}

<h4>Summary</h4>

{% render_table SummaryTable %}

{% endblock %}

templates/trade_match.html
{% extends "base_generic.html" %}

{% block content %}
<!DOCTYPE html>
<html lang="en">

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <style>
    label.center {
      margin-left: auto;
      margin-right: auto;
      width: 25em;
      text-align: center;
    }

    input.center{
      display: block;
      margin-right: auto;
      margin-left: auto;
    }

    button.center{
      display: block;
      margin-right: auto;
      margin-left: auto;
    }

    button.match_center{
      display: block;
      margin-right: auto;
      margin-left: auto;
    }
  </style>

  <h4> Match Trades </h4>

  <div>
    <form method="post">
      <div class="row">
        <div class="col-lg-4">
          {% csrf_token %}
          <table>
            {{ tradeForm.saleF }}
          </table>
        </div>
      </div>

      <br>

      <div class="row">
        <div class="col-lg-4">
          <label class="center">Unmatched Purchases</label>

          <!--<select multiple id="id_all_purchases"></select>-->
          {{ tradeForm.all_purchases }}
        </div>

        <div class="col-lg-2">
          <label class="center">Shares</label>
          <input class="center" id="id_purch_shares" size="4" value = "0"></input>
          <br>
          <button class="match_center" id="id_match_trade" type="button">Match</button>
        </div>

        <div class="col-lg-4">
          <label class="center">Matched Buys</label>
          <!--<select multiple id='id_matched_trades'></select>-->
          {{ tradeForm.matched_trades }}
        </div>
      </div>

      <br>
      <br>

      <button class="center" type="submit" value="{{b.id}}" name="pullData">Match Trade</button>
    </form>
  </div>

  <script>
    var $purch = $("#id_all_purchases");
    var $mat_tr = $("#id_match_trade");
    var $matpurch = $("#id_matched_trades")

    $( "button.match_center" ).on( 'click', function(){
      //alert($("#id_purch_shares").val());

      var mTr = $purch.find(":selected").val() + "|" + $("#id_purch_shares").val()
      var mText = $purch.find(":selected").text()

      $matpurch.append('<option value=' + mTr + '>' + mText + '</option>');
      $matpurch.val(mTr).prop('selected', true)

      return false;
    });

    $purch.on( 'change', function(){
      var trMat = $purch.find(":selected").text().split(" ");
      $("#id_purch_shares").val(trMat[1]);
    })

    $('#id_saleF').on('change', function() {
      var sale= $(this).val();
      $purch.empty();

      $.ajax({
        url: '{% url "load_buys" %}',
        data: {
          'purchases': sale
        },
        dataType: 'json',
        success: function (data)
        {
          $.each(JSON.parse(data) , function(key, value)
            {
              $purch.append('<option value=' + key + '>' + value + '</option>');
            });
        }
      });
    });

  </script>
</html>
{% endblock %}